(define (sum-larger-squares a b c)
        (define (square x) (* x x))
        (define (larger-two)
                (define (larger x y)
                        (if (> x y) x y))
                (if (= (larger a b) (larger a c))
                    (cons (larger a b) (larger b c))
                    (cons (larger a b) (larger a c))))
        (let ((nums (larger-two)))
             (+ (square (car nums)) (square (cdr nums)))))
